version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mariadb
    volumes:
      - .:/app
    environment:
      DB_DSN: ${DB_USER:-web}:${DB_PASSWORD:-123456}@tcp(mariadb:3306)/${DB_NAME:-snippetbox}?parseTime=true
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-snippetbox}
      MYSQL_USER: ${DB_USER:-web}
      MYSQL_PASSWORD: ${DB_PASSWORD:-123456}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
