services:
  - type: web
    name: snippetbox
    env: go
    buildCommand: go build -o ./bin/snippetbox ./cmd/web
    startCommand: ./bin/snippetbox
    envVars:
      - key: DB_DSN
        sync: false
